### ISSUE TITLE
Riso nai yamena na repo?

### ISSUE THREAD

**Issue by pancaek** [jiyometrik/laskuszirulivre#3]
> Package luatex.def Error: File `hinariso.pdf' not found: using draft setting.

**Comment by pancaek** [comment]
A, da se
[*.pdf](https://github.com/jiyometrik/laskuszirulivre/blob/df58f55f24cde952848ebfd4993040bf50d5e280/.gitignore#L27)
lakiti `main.pdf`?

**Comment by jiyometrik** [comment]
fiksena
